cd ..;
cd amazonData;
[a,b]=wrapper('sparseMatrix.csv', 'wordlist.csv', 'a');
printCSV('amazonOutput_a_15_cov.txt', a, b);
[a,b]=wrapper('sparseMatrix.csv', 'wordlist.csv', 'b');
printCSV('amazonOutput_b_15_cov.txt', a, b);
cd ..;
cd reutersData;
[a,b]=wrapper('sparseMatrix.csv', 'wordlist.csv', 'a');
printCSV('reutersOutput_a_15_cov.txt', a, b);
[a,b]=wrapper('sparseMatrix.csv', 'wordlist.csv', 'b');
printCSV('reutersOutput_b_15_cov.txt', a, b);
cd ..;
cd nsfData\\nsfnew;
[a,b]=wrapper('sparseMatrix.csv', 'wordlist.csv', 'a');
printCSV('nsfOutput_a_15_cov.txt', a, b);
[a,b]=wrapper('sparseMatrix.csv', 'wordlist.csv', 'b');
printCSV('nsfOutput_b_15_cov.txt', a, b);